name: parkspace
description: ParkSpace - Smart parking flutter app


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^0.5.25
  geolocator: ^7.0.3
  url_launcher: ^6.0.3
  http: ^0.13.1
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  cloud_firestore: ^2.0.0
  firebase_analytics: ^8.0.3
  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.0.0
  line_icons: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  flutter_sparkline: ^0.1.0
  firebase_database: ^6.1.2
  syncfusion_flutter_charts: ^19.1.64
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/map_style.json
    - assets/icon.png
    - assets/car.png
    - assets/time.png

